country_languages = {
    "Afghanistan": "Pashto",
    "Albania": "Albanian",
    "Algeria": "Arabic",
    "Andorra": "Catalan",
    "Angola": "Portuguese",
    "Antigua and Barbuda": "English",
    "Argentina": "Spanish",
    "Armenia": "Armenian",
    "Australia": "English",
    "Austria": "German",
    "Azerbaijan": "Azerbaijani",
    "Bahamas": "English",
    "Bahrain": "Arabic",
    "Bangladesh": "Bengali",
    "Barbados": "English",
    "Belarus": "Belarusian",
    "Belgium": "Dutch",
    "Belize": "English",
    "Benin": "French",
    "Bhutan": "Dzongkha",
    "Bolivia": "Spanish",
    "Bosnia and Herzegovina": "Bosnian",
    "Botswana": "English",
    "Brazil": "Portuguese",
    "Brunei": "Malay",
    "Bulgaria": "Bulgarian",
    "Burkina Faso": "French",
    "Burundi": "Kirundi",
    "Cabo Verde": "Portuguese",
    "Cambodia": "Khmer",
    "Cameroon": "French",
    "Canada": "English",
    "Central African Republic": "French",
    "Chad": "French",
    "Chile": "Spanish",
    "China": "Chinese",
    "Colombia": "Spanish",
    "Comoros": "Comorian",
    "Congo (Congo-Brazzaville)": "French",
    "Congo (Democratic Republic) (Congo-Kinshasa)": "French",
    "Costa Rica": "Spanish",
    "Croatia": "Croatian",
    "Cuba": "Spanish",
    "Cyprus": "Greek",
    "Czech Republic": "Czech",
    "Denmark": "Danish",
    "Djibouti": "French",
    "Dominica": "English",
    "Dominican Republic": "Spanish",
    "Ecuador": "Spanish",
    "Egypt": "Arabic",
    "El Salvador": "Spanish",
    "Equatorial Guinea": "Spanish",
    "Eritrea": "Tigrinya",
    "Estonia": "Estonian",
    "Eswatini": "Swati",
    "Ethiopia": "Amharic",
    "Fiji": "English",
    "Finland": "Finnish",
    "France": "French",
    "Gabon": "French",
    "Gambia": "English",
    "Georgia": "Georgian",
    "Germany": "German",
    "Ghana": "English",
    "Greece": "Greek",
    "Grenada": "English",
    "Guatemala": "Spanish",
    "Guinea": "French",
    "Guinea-Bissau": "Portuguese",
    "Guyana": "English",
    "Haiti": "French",
    "Honduras": "Spanish",
    "Hungary": "Hungarian",
    "Iceland": "Icelandic",
    "India": "Hindi",
    "Indonesia": "Indonesian",
    "Iran": "Persian",
    "Iraq": "Arabic",
    "Ireland": "English",
    "Israel": "Hebrew",
    "Italy": "Italian",
    "Jamaica": "English",
    "Japan": "Japanese",
    "Jordan": "Arabic",
    "Kazakhstan": "Kazakh",
    "Kenya": "Swahili",
    "Kiribati": "English",
    "Korea, North": "Korean",
    "Korea, South": "Korean",
    "Kosovo": "Albanian",
    "Kuwait": "Arabic",
    "Kyrgyzstan": "Kyrgyz",
    "Laos": "Lao",
    "Latvia": "Latvian",
    "Lebanon": "Arabic",
    "Lesotho": "Sesotho",
    "Liberia": "English",
    "Libya": "Arabic",
    "Liechtenstein": "German",
    "Lithuania": "Lithuanian",
    "Luxembourg": "Luxembourgish",
    "Madagascar": "Malagasy",
    "Malawi": "Chichewa",
    "Malaysia": "Malay",
    "Maldives": "Dhivehi",
    "Mali": "French",
    "Malta": "Maltese",
    "Marshall Islands": "Marshallese",
    "Mauritania": "Arabic",
    "Mauritius": "English",
    "Mexico": "Spanish",
    "Micronesia": "English",
    "Moldova": "Romanian",
    "Monaco": "French",
    "Mongolia": "Mongolian",
    "Montenegro": "Montenegrin",
    "Morocco": "Arabic",
    "Mozambique": "Portuguese",
    "Myanmar (Burma)": "Burmese",
    "Namibia": "English",
    "Nauru": "Nauruan",
    "Nepal": "Nepali",
    "Netherlands": "Dutch",
    "New Zealand": "English",
    "Nicaragua": "Spanish",
    "Niger": "French",
    "Nigeria": "English",
    "North Macedonia": "Macedonian",
    "Norway": "Norwegian",
    "Oman": "Arabic",
    "Pakistan": "Urdu",
    "Palau": "Palauan",
    "Panama": "Spanish",
    "Papua New Guinea": "English",
    "Paraguay": "Spanish",
    "Peru": "Spanish",
    "Philippines": "Filipino",
    "Poland": "Polish",
    "Portugal": "Portuguese",
    "Qatar": "Arabic",
    "Romania": "Romanian",
    "Russia": "Russian",
    "Rwanda": "Kinyarwanda",
    "Saint Kitts and Nevis": "English",
    "Saint Lucia": "English",
    "Saint Vincent and the Grenadines": "English",
    "Samoa": "Samoan",
    "San Marino": "Italian",
    "São Tomé and Príncipe": "Portuguese",
    "Saudi Arabia": "Arabic",
    "Senegal": "French",
    "Serbia": "Serbian",
    "Seychelles": "English",
    "Sierra Leone": "English",
    "Singapore": "English",
    "Slovakia": "Slovak",
    "Slovenia": "Slovene",
    "Solomon Islands": "English",
    "Somalia": "Somali",
    "South Africa": "Zulu",
    "South Sudan": "English",
    "Spain": "Spanish",
    "Sri Lanka": "Sinhala",
    "Sudan": "Arabic",
    "Suriname": "Dutch",
    "Sweden": "Swedish",
    "Switzerland": "German",
    "Syria": "Arabic",
    "Taiwan": "Mandarin",
    "Tajikistan": "Tajik",
    "Tanzania": "Swahili",
    "Thailand": "Thai",
    "Timor-Leste": "Tetum",
    "Togo": "French",
    "Tonga": "Tongan",
    "Trinidad and Tobago": "English",
    "Tunisia": "Arabic",
    "Turkey": "Turkish",
    "Turkmenistan": "Turkmen",
    "Tuvalu": "Tuvaluan",
    "Uganda": "English",
    "Ukraine": "Ukrainian",
    "United Arab Emirates": "Arabic",
    "United Kingdom": "English",
    "United States of America": "English",
    "Uruguay": "Spanish",
    "Uzbekistan": "Uzbek",
    "Vanuatu": "Bislama",
    "Vatican City": "Italian",
    "Venezuela": "Spanish",
    "Vietnam": "Vietnamese",
    "Yemen": "Arabic",
    "Zambia": "English",
    "Zimbabwe": "English"
}
